"use client";

import { useState, useEffect } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import type { UserProfile } from "@/types/user-profile";
import { Brain, Calendar, Clock, Loader2 } from "lucide-react";
import { FloatingTips } from "@/components/ui/FloatingTips";

interface ScheduleItem {
  day: string;
  time: string;
  subject: string;
  activity: string;
  duration: number;
}

interface StudyPlan {
  schedule: ScheduleItem[];
  tips: string[];
}

export function AdaptiveLearningPath({
  userProfile,
}: {
  userProfile: UserProfile;
}) {
  const [studyPlan, setStudyPlan] = useState<StudyPlan | null>(null);
  const [isGenerating, setIsGenerating] = useState(true);

  useEffect(() => {
    const generatePlan = async () => {
      setIsGenerating(true);
      try {
        const response = await fetch("/api/generate-study-schedule", {
          // We will create this new API route
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ userProfile }),
        });
        const data = await response.json();
        setStudyPlan(data.plan);
      } catch (error) {
        console.error("Error generating study plan:", error);
      } finally {
        setIsGenerating(false);
      }
    };
    generatePlan();
  }, [userProfile]);

  if (isGenerating) {
    return (
      <Card className="border-0 shadow-2xl bg-white/90 dark:bg-gray-900/80 backdrop-blur-xl rounded-2xl transition-all duration-300 hover:shadow-3xl hover:-translate-y-1 animate-fade-in">
        <CardContent className="flex flex-col items-center justify-center py-12">
          <Loader2 className="h-12 w-12 text-indigo-500 dark:text-indigo-400 animate-spin mb-4 drop-shadow-md" />
          <h3 className="text-lg font-semibold mb-2 text-gray-900 dark:text-gray-100">
            AI is building your personalized weekly schedule...
          </h3>
          <p className="text-gray-600 dark:text-gray-300 text-center">This will take just a moment</p>
        </CardContent>
      </Card>
    );
  }

  if (!studyPlan) {
    return (
      <Card className="border-0 shadow-2xl bg-white/90 dark:bg-gray-900/80 backdrop-blur-xl rounded-2xl transition-all duration-300 hover:shadow-3xl hover:-translate-y-1 animate-fade-in">
        <CardContent>
          <p className="text-center py-8 text-gray-700 dark:text-gray-300">
            Could not generate a study plan. Please try again later.
          </p>
        </CardContent>
      </Card>
    );
  }

  const daysOfWeek = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ];

  return (
    <div className="space-y-6 animate-fade-in">
      <Card className="border-0 shadow-2xl bg-white/90 dark:bg-gray-900/80 backdrop-blur-xl rounded-2xl transition-all duration-300 hover:shadow-3xl hover:-translate-y-1 animate-bounce-slow">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 font-extrabold text-blue-700 dark:text-blue-300">
            <Calendar className="h-6 w-6 text-blue-600 dark:text-blue-400 drop-shadow-md" />
            Your Weekly Study Plan
          </CardTitle>
          <CardDescription className="text-gray-600 dark:text-gray-300">
            A personalized timetable generated by AI based on your subjects,
            availability, and learning preferences.
          </CardDescription>
        </CardHeader>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 xl:grid-cols-4 gap-4 animate-fade-in delay-200">
        {daysOfWeek.map((day, dayIndex) => {
          const daySchedule = studyPlan.schedule.filter(
            (item) => item.day === day
          );
          return (
            <Card key={day} className="flex flex-col border-0 shadow-2xl bg-white/90 dark:bg-gray-900/80 backdrop-blur-xl rounded-2xl transition-all duration-300 hover:shadow-3xl hover:-translate-y-1 animate-bounce-slow" style={{ animationDelay: `${dayIndex * 100}ms` }}>
              <CardHeader className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/50 dark:to-indigo-900/50 rounded-t-2xl">
                <CardTitle className="text-center text-lg font-extrabold text-blue-700 dark:text-blue-300">{day}</CardTitle>
              </CardHeader>
              <CardContent className="p-4 space-y-3 flex-grow">
                {daySchedule.length > 0 ? (
                  daySchedule.map((item, index) => (
                    <div key={index} className="p-3 bg-white/80 dark:bg-gray-800/80 rounded-lg border border-blue-200 dark:border-blue-800 hover:shadow-md transition-all duration-200 hover:scale-105">
                      <p className="font-semibold text-gray-900 dark:text-gray-100">{item.subject}</p>
                      <p className="text-sm text-gray-700 dark:text-gray-300">{item.activity}</p>
                      <div className="flex items-center justify-between text-xs text-gray-500 dark:text-gray-400 mt-2">
                        <span className="flex items-center">
                          <Clock className="inline h-3 w-3 mr-1 text-blue-500 dark:text-blue-400" />
                          {item.time}
                        </span>
                        <span className="bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300 px-2 py-1 rounded-full text-xs font-semibold">{item.duration} mins</span>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="flex flex-col items-center justify-center py-8">
                    <div className="w-12 h-12 bg-gray-100 dark:bg-gray-800 rounded-full flex items-center justify-center mb-2">
                      <span className="text-2xl">😴</span>
                    </div>
                    <p className="text-center text-gray-500 dark:text-gray-400 font-medium">Rest Day</p>
                  </div>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>
      <FloatingTips tips={studyPlan.tips} />
    </div>
  );
}
